version: '3.2'

services:
  php:
    build:
      context: ./docker/php
    working_dir: /srv
    volumes:
      - ./:/srv/
    networks:
      nalbb: ~

  database:
    image: postgres:12
    working_dir: /srv
    volumes:
      - database:/usr/local/var/postgres
    ports:
      - "127.0.0.1:8432:5432"
    environment:
      - POSTGRES_PASSWORD=nalbb
      - POSTGRES_DB=nalbb
    networks:
      nalbb: ~


  nginx:
      image: nginx:1.21-alpine
      depends_on:
          - php
      volumes:
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
          - ./public:/srv/public:ro
          - ./var/log/nginx:/var/log/nginx
      ports:
          - "8044:80"

volumes:
  database: ~

networks:
  nalbb: ~